// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QH-B0NRJ64wwsS9UADOSO9NAC4WzZn8',
    appId: '1:69598828189:web:45e3154087a9130b396674',
    messagingSenderId: '69598828189',
    projectId: 'ehsola-dc80f',
    authDomain: 'ehsola-dc80f.firebaseapp.com',
    storageBucket: 'ehsola-dc80f.appspot.com',
    measurementId: 'G-SS132RM4ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-RgvRE-ooX0sbNAFzcXIneohOHR5M-Y',
    appId: '1:69598828189:android:a09511d6416f3b05396674',
    messagingSenderId: '69598828189',
    projectId: 'ehsola-dc80f',
    storageBucket: 'ehsola-dc80f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8WlPysJadiWvN6QQIuKT6nl6xsRUdXk',
    appId: '1:69598828189:ios:bfce583858f1e60b396674',
    messagingSenderId: '69598828189',
    projectId: 'ehsola-dc80f',
    storageBucket: 'ehsola-dc80f.appspot.com',
    iosClientId:
        '69598828189-rj9oog8uludqpmh8icj24morcf3q5vpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8WlPysJadiWvN6QQIuKT6nl6xsRUdXk',
    appId: '1:69598828189:ios:bfce583858f1e60b396674',
    messagingSenderId: '69598828189',
    projectId: 'ehsola-dc80f',
    storageBucket: 'ehsola-dc80f.appspot.com',
    iosClientId:
        '69598828189-rj9oog8uludqpmh8icj24morcf3q5vpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
